# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'JourneySmart' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTImage',
    'RCTNetwork',
    'RCTText',
    'RCTWebSocket',
    'BatchedBridge',
    # Add any other subspecs you want to use in your project
  ]
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  pod 'react-native-background-timer', :path => '../node_modules/react-native-background-timer'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'GoogleSignIn'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'
  pod 'react-native-sqlite-storage', :path => '../node_modules/react-native-sqlite-storage'
  # Pods for JourneySmart


end

target 'JourneySmart-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JourneySmart-tvOS


end
